server:
  port: 8888
  servlet:
    context-path: /seedTrade
spring:
  datasource:
    url: jdbc:mysql://118.25.88.251:3306/seekTrade?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 2000
    hikari:
      max-lifetime: 1200000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true